In [1]:
import numpy as np

In [20]:
myarr = np.array([[2,1,3,4]])

In [21]:
myarr.shape


(1, 4)

In [25]:
myarr[0][1]

1

In [26]:
myarr.size

4

In [27]:
zeros = np.zeros((2,5))

In [28]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
zeros.size

10

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
np.linspace(1,5,12)

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [32]:
np.identity(45)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
np.arange(99)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr = np.arange(99).reshape(3,33)

In [39]:
arr.sum(axis=1)

array([ 528, 1617, 2706])

In [40]:
arr.sum(axis=0)

array([ 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135,
       138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171, 174,
       177, 180, 183, 186, 189, 192, 195])

In [41]:
arr.T

array([[ 0, 33, 66],
       [ 1, 34, 67],
       [ 2, 35, 68],
       [ 3, 36, 69],
       [ 4, 37, 70],
       [ 5, 38, 71],
       [ 6, 39, 72],
       [ 7, 40, 73],
       [ 8, 41, 74],
       [ 9, 42, 75],
       [10, 43, 76],
       [11, 44, 77],
       [12, 45, 78],
       [13, 46, 79],
       [14, 47, 80],
       [15, 48, 81],
       [16, 49, 82],
       [17, 50, 83],
       [18, 51, 84],
       [19, 52, 85],
       [20, 53, 86],
       [21, 54, 87],
       [22, 55, 88],
       [23, 56, 89],
       [24, 57, 90],
       [25, 58, 91],
       [26, 59, 92],
       [27, 60, 93],
       [28, 61, 94],
       [29, 62, 95],
       [30, 63, 96],
       [31, 64, 97],
       [32, 65, 98]])

In [44]:
for i in range(arr.shape[0]): 
    sum=0
    for j in range(arr.shape[1]):
        sum+=arr[i][j]
    print(sum)

528
1617
2706


In [45]:
arr.argmax()

98

In [46]:
arr.argmin()

0

In [47]:
arr.argmax(axis=0)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [48]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [52]:
arr =arr.ravel()

In [55]:
ar1 = np.array([[4,5,6],
               [1,2,3],
               [10,11,12]])
ar2 = np.array([[4,5,6],
               [1,2,3],
               [10,11,12]])
ar1 + ar2

array([[ 8, 10, 12],
       [ 2,  4,  6],
       [20, 22, 24]])

In [56]:
np.sqrt(ar1)

array([[2.        , 2.23606798, 2.44948974],
       [1.        , 1.41421356, 1.73205081],
       [3.16227766, 3.31662479, 3.46410162]])

In [57]:
ar1.sum()

54

In [58]:
ar1.max()

12

In [59]:
ar1.min()

1

In [61]:
np.where(ar1>5)

(array([0, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [62]:
np.count_nonzero(ar1)

9

In [65]:
np.count_nonzero(ar1==0)

0

True