In [1]:
import numpy as np
import pandas as  pd
import tensorflow as tf

In [2]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
X = dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [4]:
X


array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [5]:
y = y.reshape(len(y),1)
y

array([[463.26],
       [444.37],
       [488.56],
       ...,
       [429.57],
       [435.74],
       [453.28]])

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)
y_train = sc_y.fit_transform(y_train)


In [8]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [9]:
ann.add(tf.keras.layers.Dense(units=1))

In [17]:
ann.compile(optimizer="adam", loss="mean_squared_error")

In [18]:
ann.fit(X_train, y_train, batch_size=20, epochs=70)

Train on 7654 samples
Epoch 1/70
7654/7654 [==============================] - 1s 148us/sample - loss: 0.0618
Epoch 2/70
7654/7654 [==============================] - 1s 78us/sample - loss: 0.0618
Epoch 3/70
7654/7654 [==============================] - 1s 91us/sample - loss: 0.0616
Epoch 4/70
7654/7654 [==============================] - 1s 90us/sample - loss: 0.0614
Epoch 5/70
7654/7654 [==============================] - 1s 107us/sample - loss: 0.0616
Epoch 6/70
7654/7654 [==============================] - 1s 89us/sample - loss: 0.0616
Epoch 7/70
7654/7654 [==============================] - 1s 110us/sample - loss: 0.0616
Epoch 8/70
7654/7654 [==============================] - 1s 111us/sample - loss: 0.0615
Epoch 9/70
7654/7654 [==============================] - 1s 109us/sample - loss: 0.0614
Epoch 10/70
7654/7654 [==============================] - 1s 108us/sample - loss: 0.0615
Epoch 11/70
7654/7654 [==============================] - 1s 86us/sample - loss: 0.0613
Epoch 12/70
7654/7654 [=

In [19]:
y_test=y_test.reshape(1,len(y_test))

In [20]:
y_test=y_test.ravel()

In [21]:
y_test

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [22]:
y_pred=sc_y.inverse_transform(ann.predict(X_test))

In [23]:
np.concatenate((y_pred, y_test.reshape(len(y_test),1)), axis=1)

array([[432.12576294, 431.23      ],
       [455.19747925, 460.01      ],
       [460.17095947, 461.14      ],
       ...,
       [469.18432617, 473.26      ],
       [438.8710022 , 438.        ],
       [461.65341187, 463.28      ]])

In [26]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9452220612653696