In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
dataset  = pd.read_csv("Social_Network_Ads.csv")

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
print(X_test)

[[-0.76263275  0.57401558]
 [-0.00567717 -0.53079239]
 [-0.47877441 -1.19949195]
 [ 0.27818118 -0.70523575]
 [ 0.08894228 -0.79245743]
 [-0.10029662  0.22512885]
 [-1.0464911   0.42864611]
 [-0.76263275 -1.57745257]
 [-0.76263275  1.09734567]
 [-0.76263275  0.51586779]
 [-1.0464911   0.54494168]
 [-1.0464911  -1.51930478]
 [-0.57339386  0.4867939 ]
 [-0.8572522   0.39957221]
 [-0.66801331  0.13790717]
 [-0.28953551  0.22512885]
 [-1.89806614 -0.50171849]
 [-0.10029662 -0.21097956]
 [ 0.56203952  2.02771027]
 [-0.28953551 -0.24005345]
 [ 1.12975621 -0.9669008 ]
 [ 1.03513677 -1.19949195]
 [-0.47877441  1.27178903]
 [ 0.18356173 -0.35634903]
 [-0.28953551 -1.37393531]
 [ 0.27818118  0.07975938]
 [-0.28953551 -0.29820124]
 [ 0.84589787 -0.53079239]
 [-0.28953551  0.16698106]
 [-0.28953551  0.10883328]
 [ 0.65665897 -1.37393531]
 [-0.00567717 -0.24005345]
 [ 1.8867118   2.17307974]
 [-1.80344669 -1.4030092 ]
 [-0.28953551  0.80660673]
 [-1.61420779  0.54494168]
 [-0.95187165  0.57401558]
 

In [19]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
lg.fit(X_train, y_train)

C:\Users\gs935\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [40]:
y_pred=lg.predict([[X_test[0][0], X_test[0][1]]])
print(X_test[0][0],X_test[0][1])
y_pred_prob=lg.predict_proba([[X_test[0][0], X_test[0][1]]])
y_pred_prob

-0.762632754291014 0.5740155768711028


array([[0.89879265, 0.10120735]])

In [46]:
y_pred_total = lg.predict(X_test)

In [48]:
np.concatenate((y_pred_total.reshape(len(y_pred_total),1), y_test.reshape(len(y_test),1)),axis=1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0,

In [29]:
ans = y_pred==y_test

In [30]:
ans

array([[ True,  True,  True, ..., False,  True, False],
       [ True,  True,  True, ..., False,  True, False],
       [ True,  True,  True, ..., False,  True, False],
       ...,
       [ True,  True,  True, ..., False,  True, False],
       [False, False, False, ...,  True, False,  True],
       [False, False, False, ...,  True, False,  True]])

In [52]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred_total)
print(cm)
accuracy_score(y_test, y_pred_total)

[[64  2]
 [12 22]]


0.86